### ISSUE TITLE
Why not extend-type on JFreeChart itself?

### ISSUE THREAD

**Issue by spieden** [JonyEpsilon/incanter-gorilla#3]
Just curious why you didn't choose to extend-type on JFreeChart directly? For example I did this and it worked fine:

``` clojure
(extend-type org.jfree.chart.JFreeChart
  render/Renderable
  (render [self] (render/render (chart-view self))))
```

i.e. I don't need to use chart-view directly after evaluating this form to see the charts in Gorilla.

**Comment by JonyEpsilon** [comment]
I think a couple of reasons:
- there needs to be somewhere to pass in the options, and if the charts render directly then you can't do that.
- it felt more natural to me, because when you call chart-view you're taking a snapshot of the (mutable) chart, and the value that Gorilla actually renders is that (immutable) snapshot. So it seemed right to have a function that made that step explicit.
